service: video-upload

frameworkVersion: "3"
package:
  individually: true

provider:
  name: aws
  stage: dev
  runtime: nodejs20.x
  region: us-east-1
  environment:
    BUCKET_NAME: teste-fase5
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: arn:aws:s3:::teste-fase5/*

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    external:
      - knex
    watch:
      pattern: "src/**/*.ts"
      ignore: "**/*.test.ts"

plugins:
  - serverless-esbuild
  - serverless-offline

functions:
  get-images:
    handler: src/api/handlers/get-images/handler.handler
    events:
      - http:
          method: GET
          path: /processed/{videoId}
